# Generated by Django 4.1 on 2022-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_itemimages_options_alter_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
