# Generated by Django 4.1 on 2022-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_categories_image_alter_itemimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Основное изображение'),
        ),
    ]
