# Generated by Django 4.1 on 2022-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='items',
            name='main_image',
            field=models.ImageField(default='no-image.png', upload_to='', verbose_name='Основное изображение'),
        ),
    ]
