# Generated by Django 4.1 on 2022-08-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_categories_image_alter_items_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimages',
            old_name='item',
            new_name='of_item',
        ),
    ]
