# Generated by Django 4.1 on 2022-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_categories_image_alter_itemimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='media/no-image.png', upload_to='media/category_covers', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='items',
            name='main_image',
            field=models.ImageField(default='media/no-image.png', upload_to='media/item_covers', verbose_name='Основное изображение'),
        ),
    ]
