# Generated by Django 4.1 on 2022-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_categories_image_alter_items_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimages',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись'),
        ),
    ]
