# Generated by Django 4.1 on 2022-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_itemimages_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Подпись'),
        ),
    ]
