# Generated by Django 4.1 on 2022-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_itemimages_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Только для избранных'),
        ),
    ]
