# Generated by Django 4.1 on 2022-08-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_categories_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название категории'),
        ),
    ]
