# Generated by Django 4.1 on 2022-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='main_image',
            field=models.ImageField(default='no-image.png', upload_to='item_covers', verbose_name='Основное изображение'),
        ),
    ]
