# Generated by Django 4.1 on 2022-10-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_categories_image_alter_itemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='item_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название товара'),
        ),
    ]
