# Generated by Django 4.1 on 2022-10-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_itemimages_image_alter_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
