# Generated by Django 4.1 on 2022-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_items_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='currency_price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=25, verbose_name='Цена (в валюте)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена (в рублях)'),
        ),
    ]
