# Generated by Django 4.1 on 2022-10-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_items_currency_price_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='currency_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (в валюте)'),
        ),
    ]
